apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: app
          command: ["/bin/sh","-c"]
          args: ["poetry run python src/medsearch_api/run_api.py"]
          env:
            - name: PYTHONPATH
              value: "/medsearch/src"
            - name: MYSQL_LOGGING
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_LOGGING
                  name: env
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: env
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_PORT
                  name: env
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  key: ENV
                  name: env
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_HOST
                  name: env
            - name: MYSQL_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MYSQL_ADMIN_USER
            - name: MYSQL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MYSQL_ADMIN_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MYSQL_PASSWORD
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
      restartPolicy: Always
